### ISSUE TITLE
Inference test returns error

### ISSUE THREAD

**Issue by brunotakara** [neuronflow/AURORA#1]
Hi, thanks for sharing your project! I cloned your repo on VSCode and tried to run inference on 4 mri and 1 mask stored as nii.gz files, but I got the following error when applying transforms, do you have any insight of what am I doing wrong?

> File "C:\Users\bruno.takara\AppData\Roaming\Python\Python39\site-packages\monai\transforms\transform.py", line 113, in apply_transform
>     raise RuntimeError(f"applying transform {transform}") from e
> RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x00000190C0038130>

The error begins at this line on lib.py:

>   File "d:\Bruno\AURORA\AURORA\lib.py", line 219, in single_inference
>     for counter, data in enumerate(tqdm(data_loader, 0)):
>   File "C:\Users\bruno.takara\AppData\Roaming\Python\Python39\site-packages\tqdm\std.py", line 1195, in __ iter__
>     for obj in iterable:
>   File "C:\Users\bruno.takara\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 530, in __ next__
>     data = self._next_data()
>   File "C:\Users\bruno.takara\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

Thanks!

**Comment by neuronflow** [comment]
Thanks for your interest in our package. Would you like to share some details about your system?

It seems you are using Windows? Python version?

Can you copy-paste the full error message?

PS: We will retire this repo soon, please have a look at our new BrainLes Aurora package which we are currently actively developing:
https://github.com/BrainLesion/AURORA

You can find a small tutorial here:
https://github.com/BrainLesion/tutorials/blob/main/AURORA/tutorial.ipynb

We highly appreciate feedback :)

**Comment by brunotakara** [comment]
Thanks for your reply, I will certainly have a look at your most recent project!

Yes, it is Windows with Python version 3.9.12 ('base': conda). I did not realize it wasn't the full error, so I checked the whole error and figured it out that I was inputting relative path instead of whole path to the files ><" Now it seems alright but I am running out of GPU memory (8GB), is it possible to run it on cpu  (64GB RAM)? I tried switching `cuda_devices = 'cpu'` but I got stuck on 0%

**Comment by neuronflow** [comment]
8GB VRAM should be sufficient, you can play around with the sliding window batch size as demonstrated in the tutorial when running oom:
https://github.com/BrainLesion/tutorials/blob/main/AURORA/tutorial.ipynb

Note that you will need a Python 3.10 env as we heavily leverage P3.10 functionality.

**Comment by brunotakara** [comment]
Reducing the sliding window worked well! Alright, I will install Python 3.10 before trying BrainLesion. Thanks for your help!

**Comment by neuronflow** [comment]
Yes, just make sure, you do not reduce the window size but the batch size unless you know what you are doing :)
